language: python
addons:
  apt:
    packages:
    - g++
    - zlib1g-dev
    - check
    - autoconf
    - libtool
    - git
    - python-dev
    - libblas-dev
    - liblapack-dev
    - gfortran
cache:
  directories:
  - "prototype/build"
  - "$HOME/.cache/pip"
python:
  - "2.7"
sudo: false
before_install:
  - "pip install --upgrade pip"
  - "pip --version"
install:
  - "cd prototype"
  - "source ./install_dependencies.sh"
  - "cd .."
  - "travis_wait pip install -r requirements.txt"
  - "python setup.py develop"
script: "./run_tests.sh"
