language: python
python:
 - "2.7"
sudo: required
before_install:
  - "pip install --upgrade pip"
  - "pip --version"
install:
  - "cd prototype"
  - "sudo pip install -r invoke_requirements.txt"
  - "sudo invoke install"
  - "export LD_LIBRARY_PATH=/usr/local/lib"
  - "cd .."
  - "travis_wait pip install -r requirements.txt"
  - "python setup.py develop"
script: "./run_tests.sh"
