language: python
python:
 - "2.7"
sudo: required
install:
  - "cd prototype"
  - "pip install invoke_requirements.txt"
  - "sudo invoke install"
  - "export LD_LIBRARY_PATH=/usr/local/lib"
  - "cd .."
  - "pip install requirements.txt"
  - "python setup.py develop"
script: "./run_tests.sh"
