#!/usr/bin/env python

import argparse
import os
import sys

from argparse import FileType, ArgumentError

from biopericles.ClusterConsensus import ClusterConsensus

def stderr(text):
  print >> sys.stderr, text

def get_cluster_name(path):
  filename = os.path.basename(path)
  name = os.path.splitext(filename)[0] # remove extension
  return name

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.description = "Find areas of consensus between aligned sequences in a multifasta"
  parser.add_argument('multifasta', nargs="+", type=FileType(mode='r'),
                      help="Multifasta with aligned sequences")
  parser.add_argument('--output', '-o', dest="output_file", type=str, default='-',
                      help="Output file (defaults to stdout)")

  args = parser.parse_args()

  cluster = ClusterConsensus()
  cluster.load_fasta_file(args.multifasta)

  cluster_name = get_cluster_name(args.multifasta.name)
  cluster.cluster_name = cluster_name

  if args.output_file == '-':
    cluster.output_file = sys.stdout
    cluster.write_consensus()
  else:
    try:
      with open(args.output_file, 'w') as output_file:
        cluster.output_file = output_file
        cluster.write_consensus()
    except IOError as e:
      message = """\
Could not open output file '{output_file}' for writing, exiting without doing any work.
Original error:
{exception}"""
      stderr(message.format(output_file=args.output, exception=e))
      exit(1)
